---
title: "COVID-19"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
runtime: shiny_prerendered
---

```{r todods,include=F}
# TODO: Animate the bar charts next to the maps
# TODO: Find country populations
```

```{r setup,context="setup",include=FALSE}
library(flexdashboard)
library(shiny)
library(shinyWidgets)

# Tidyverse
library(readr)
library(dplyr)
library(magrittr)
library(lubridate)
library(tidyr)
library(purrr)
library(stringr)

# Visualizations 
library(leaflet)
library(highcharter)
library(htmltools)
library(sf)

# Other
library(jsonlite)
library(zoo)
```

```{r params,include=F,cache=F,context="setup"}
params <- list(
  k = 7,
  updateFreq = 60 * 60 * 1000
)
```


```{r setupdata,context="server-start",include=F}
dataset <- list()
datasetdt <- reactiveValues()

update_dataset_dt_file <- function(tag, file) {
  datasetdt[[tag]] <- file.mtime(file)
}

update_dataset_dt_url <- function(tag, url) {
  resp <- httr::HEAD(url)
  datasetdt[[tag]] <- dmy_hms(resp$headers$date)
}

get_url_date <- function(url) {
  resp <- httr::HEAD(url)
  dmy_hms(resp$headers$date)
}

get_new_data <- function(tag, url, f) {
  out <- read_csv(url) %>% 
    f()
  update_dataset_dt_url(tag, url)
  out 
}

makePoll <- function(tag, url, f) reactivePoll(
  intervalMillis = params$updateFreq, session = NULL, 
  checkFunc = function() get_url_date(url), 
  valueFunc = function() get_new_data(tag, url, f)
)

get_new_data_json <- function(tag, url, f) {
  out <- fromJSON(url) %>% 
    f()
  update_dataset_dt_url(tag, url)
  out 
}
```

```{r supplement_data,include=F,context="server-start"}
supplement_data_for_medical <- function(x) x %>% 
  mutate(
    hosp_rate = hospitalized / cases,
    
    active_cases = cases - (recovered + deaths), 
    active_case_growth = active_cases - dplyr::lag(active_cases, 1, default=0), 
    active_case_growth_rate = active_case_growth / dplyr::lag(active_cases, 1),
    active_case_growth_rate_ma = rollmeanr(active_case_growth_rate, k=params$k, fill=NA),
    
    text_medical = paste0(
      if_else(!is.na(active_cases), paste0("Active Cases: ", active_cases, "<br/>"), ""),
      if_else(!is.na(hospitalized), paste0("Hospitalized: ", hospitalized, "<br/>"), ""),
      if_else(!is.na(icu), paste0("ICU: ", icu, "<br/>"), ""),
      if_else(!is.na(vent), paste0("Ventilator: ", vent, "<br/>"), ""),
      if_else(!is.na(recovered), paste0("Recovered: ", recovered, "<br/>"), ""),
      if_else(!is.na(active_case_growth_rate_ma), paste0(params$k, "-Day Trailing Average Change in Active Cases / Day: ", round(active_case_growth_rate_ma * 100, 1), "%<br/>"), "")
    )
  )

supplement_data_for_demographics <- function(x) x %>% 
  mutate(
    penetrance = cases / housing_units,
    pop_density = pop / landsqmi,
    housing_density = housing_units / landsqmi,
    occupancy_density = pop / housing_units,
    
    text_demographics = paste0(
      if_else(!is.na(pop), paste0("Population: ", pop, "<br/>"), ""), 
      if_else(!is.na(pop_density), paste0("Density: ", round(pop_density, 4), " ppl/sqmi<br/>"), ""),
      if_else(!is.na(housing_density), paste0( "Housing Units: ",  round(housing_density, 4), " /sqmi<br/>"), ""),
      if_else(!is.na(penetrance), paste0("Penetrance: ", round(penetrance, 3), " cases / household<br/>"), "")
    )
  )

supplement_data_base <- function(x) x %>% 
  mutate(
      rate = round((cases / pop) * 100000),
       text_case = paste0(
        if_else(!is.na(cases), paste0("Confirmed Cases: ", cases, "<br/>"), ""), 
        if_else(!is.na(rate), paste0("Infection Rate: ", rate, " / 100,000 ppl<br/>"), ""),
        if_else(!is.na(deaths), paste0("Deaths: ", deaths, "<br/>"), "")
      )
  )

supplement_data_for_growth <- function(x) x %>% 
  mutate(
    cases_new = cases - lag(cases, 1, default = 0),
    cases_growth_rate = case_when(
      cases_new == 0 ~ 0, 
      lag(cases, 1) == 0 ~ .1, 
      TRUE ~ (cases_new / lag(cases, 1))
    ) ,
    
    new_cases_ma = rollmeanr(cases_new, k=params$k, fill=NA),
    cases_growth_rate_ma = rollmeanr(cases_growth_rate, k=params$k, fill=NA),
    
    had_increase = cases_new > new_cases_ma, 
    hot_spot = (had_increase + dplyr::lag(had_increase, 1, default=1) + dplyr::lag(had_increase, 2, default=1)) == 3, 
    
    text_growth = paste0(
      if_else(! is.na(cases_new), paste0("New Cases: ", cases_new, "<br/>"), ""), 
      if_else(! is.na(cases_growth_rate), paste0("Growth: ", round(cases_growth_rate, 3), " d/d<br/>"), ""),
      if_else(! is.na(new_cases_ma), paste0(params$k, "-Day Trailing Average New Cases / Day: ", round(new_cases_ma), "<br/>"), ""), 
      if_else(! is.na(cases_growth_rate_ma), paste0(params$k, "-Day Trailing Average Growth / Day: ", round(cases_growth_rate_ma * 100, 1), "%<br/>"), "")
    )
  )

supplement_data_for_testing <- function(x) x %>% 
  mutate(
    cum_negative = cumsum(negativeIncrease), 
    cum_pos_rate = cases / (cases + cum_negative), 
    pos_rate = positiveIncrease / (positiveIncrease + negativeIncrease), 
    tests = pending + positiveIncrease + negativeIncrease, 
    tests_per_cap = (tests / pop) * 100000, 
    tests_per_cap_ma = rollmeanr(tests_per_cap, k=params$k, fill=NA), 

    pos_rate_ma = rollsumr(positiveIncrease, k=params$k, fill=NA) / rollsumr(tests, k=params$k, fill=NA),

    text_testing = paste0(
      if_else(!is.na(tests), paste0("Tests Performed: ", tests, "<br/>"), ""),
      if_else(!is.na(tests_per_cap), paste0(params$k, "-Day Trailing Average Daily Tests / 100,000 ppl: ", round(tests_per_cap, 1), "<br/>"), ""), 
      if_else(!is.na(pending), paste0("Test Backlog: ", pending, "<br/>"), ""),
      if_else(!is.na(pos_rate), paste0("Daily Positive Rate: ", round(pos_rate * 100), "%<br/>"), ""),
      if_else(!is.na(cum_pos_rate), paste0("Positive Rate So Far: ", round(cum_pos_rate * 100), "%<br/>"), "")
    )
  )
```

```{r load_data_and_geoms,include=F,context="setup",cache=F}
load("./data/locations.Rda")
load("./data/geometries.Rda")
load("./data/region_geometries.Rda")
load("./data/zip_geoms.Rda")
load("./data/san_mateo.Rda")
load("./data/zips.Rda")
load("./data/la_polys.Rda")

geometries %<>%
  left_join(locations %>% 
              select(state = Sublocation, 
                     county = Subsublocation, 
                     loc_id)
  )

continental_us <- geometries %>%
  filter(! state %in% c("Alaska", "Hawaii")) %>% 
  ungroup() %>% 
  summarize(us = st_combine(geometry)) 

world_geoms <- region_geometries %>% 
    inner_join(
      locations %>% 
        filter(us_level == "Country") %>% 
        select(loc_id, Location, Sublocation)
      ) %>%
  mutate(
    bbox = map(geometry, ~st_bbox(.))
  )
```

```{r data_jh_and_locations,context="server-start",include=F}
url_world_confirmed <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv"
url_world_dead <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv"
url_world_recovered <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv"

process_jh_confirmed <- function(x) x %>% 
  inner_join(
    locations %>% 
      select(`Province/State`=Sublocation, `Country/Region`=Location, loc_id)
  ) %>%
  select(loc_id, matches("[0-9]+.[0-9]+.[0-9]+")) %>% 
  gather(key="date", value="cases", -loc_id)

process_jh_dead <- function(x) x %>% 
  inner_join(
    locations %>% 
      select(`Province/State`=Sublocation, `Country/Region`=Location, loc_id)
  ) %>%
  select(loc_id, matches("[0-9]+.[0-9]+.[0-9]+")) %>% 
  gather(key="date", value="deaths", -loc_id)

process_jh_recovered <- function(x) x %>% 
  inner_join(
    locations %>% 
      select(`Province/State`=Sublocation, `Country/Region`=Location, loc_id)
  ) %>%
  select(loc_id, matches("[0-9]+.[0-9]+.[0-9]+")) %>% 
  gather(key="date", value="recovered", -loc_id)

dataset$confirmed <- makePoll("Confirmed Cases (JH)", url_world_confirmed, 
                              process_jh_confirmed) 

dataset$dead <- makePoll("Confirmed Dead (JH)", url_world_dead, 
                         process_jh_dead)

dataset$recoveries <- makePoll("Confirmed Recovered (JH)", url_world_recovered, 
                               process_jh_recovered)

world_cases_jh <- reactive({
  full_join(dataset$confirmed(), dataset$dead()) %>%
    full_join(dataset$recoveries()) %>%
    group_by(loc_id) %>% 
    mutate(
      date = mdy(date)
    ) %>%
    arrange(date) %>%
    mutate(
      deaths_new = deaths - lag(deaths, 1, default=0),
      cases_new = cases - lag(cases, 1, default=0), 
      pop = NA_real_, # Find pop later for more data!
      landsqmi = NA_real_,
      housing_units = NA_real_,
      hospitalized = NA_real_,
      icu = NA_real_, 
      vent = NA_real_,
      negative = NA_real_
    ) %>% 
    supplement_data_base() %>%
    supplement_data_for_medical() %>%
    supplement_data_for_growth() 
})
```

```{r data_nytimes,context="server-start",include=F}
# ------ NY TIMES
url_ny_county <- "https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv"
url_ny_state <- "https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv"

process_ny_county <- function(x) {
  x %>% 
    left_join(
      locations %>% 
        select(county = Subsublocation, state=Sublocation, loc_id)
    ) %>%
    select(-county, -state)
}

process_ny_state <- function(x) {
  x %>% 
    filter(! state %in% c(78, 66)) %>% # Exclude virgin islands and guam
    left_join(locations %>% 
                filter(is.na(Subsublocation)) %>% 
                select(state=Sublocation, loc_id)) %>% 
    select(-state)
}

dataset$cases_county_nyt <- makePoll("NYT Counties", 
                                     url_ny_county, 
                                     process_ny_county)

dataset$cases_state_nyt <- makePoll("NYT States", 
                                    url_ny_state, 
                                    process_ny_state) 
```


```{r data_covid_track,context="server-start",include=F}
# ------------ COVID Tracking Project
url_covid_track <- "https://covidtracking.com/api/v1/states/daily.json"

process_covid_track <- function(x) x %>%
  mutate(
    date = ymd(date)
  ) %>% inner_join(
    data.frame(state = state.abb, state_full=state.name)
  ) %>% 
  select(-state) %>% 
  rename(state=state_full) %>%
  left_join(
    locations %>% filter(is.na(Subsublocation)) %>% select(state=Sublocation, loc_id)
  ) %>%
  group_by(date, loc_id) %>%
  summarize_if(is.integer, ~max(if_else(is.na(.), 0L, .))) %>%
  ungroup()

dataset$covid_track <- reactivePoll(
  intervalMillis = params$updateFreq, session=NULL,
  checkFunc = function() get_url_date(url_covid_track),
  valueFunc = function() get_new_data_json(tag="COVID Track", 
                                           url=url_covid_track, 
                                           f=process_covid_track)
)
```


```{r data_interventions,context="server-start",include=F}
# ---------------  Intervention data
url_interventions <- "https://raw.githubusercontent.com/Keystone-Strategy/covid19-intervention-data/master/complete_npis_inherited_policies.csv"

process_interventions <- function(x) x %>%
  select(county, state, intervention=npi, date=start_date, end_date) %>% 
  mutate(
    date = mdy(date), end_date = mdy(end_date)
  ) %>%
  filter(! is.na(date)) %>% 
  inner_join(locations %>% select(county=Subsublocation, state=Sublocation, loc_id)) %>% 
  select(-county, -state)

dataset$interventions <- makePoll("Interventions", url_interventions,
                                  process_interventions)
```

```{r data_nyhealth,context="server-start",include=F}
url_nyzipcode <- "https://raw.githubusercontent.com/nychealth/coronavirus-data/master/tests-by-zcta.csv"

process_nyzipcode <- function(x) x %>% 
  filter(! is.na(MODZCTA)) %>% 
  select(zipcode=MODZCTA, cases=Positive, total_tests=Total) %>%
  mutate(recovered = NA, deaths=NA, date=Sys.Date())


dataset$nyzipcode <- makePoll("NYC Testing by Zipcode", url_nyzipcode, process_nyzipcode)
```


```{r data_sfhealth,context="server-start",include=F}
url_sfzipcode <- "https://data.sfgov.org/resource/favi-qct6.csv"

process_sfzipcode <- function(x) x %>% 
  select(date = data_as_of, zipcode=zip_code, cases=count) %>%
  mutate(
    date = as.Date(date),
    recovered = NA,
    deaths = NA
  )

dataset$sfzipcode <- makePoll("SF Testing by Zipcode", 
                              url_sfzipcode, 
                              process_sfzipcode)

url_alameda <- "https://services3.arcgis.com/1iDJcsklY3l3KIjE/arcgis/rest/services/Alameda_County_COVID-19_Zip_Code_Data/FeatureServer/0/query?where=1%3D1&outFields=Zip,Count&outSR=4326&f=json"

process_alameda <- function(x) x$features$attributes %>% 
  set_colnames(c("zipcode", "cases")) %>%
  mutate(
    cases = case_when(
      str_starts(cases, "<") ~ 10, 
      TRUE ~ as.numeric(cases)
    ),
    date = Sys.Date()
  )

dataset$alameda <- reactivePoll(
  intervalMillis = params$updateFreq, session=NULL,
  checkFunc = function() get_url_date(url_alameda),
  valueFunc = function() get_new_data_json(tag="Alameda", 
                                           url=url_alameda, 
                                           f=process_alameda)
)
```

```{r data_la,context="server-start",include=F}
library(rvest)

url_la <- "http://publichealth.lacounty.gov/media/coronavirus/locations.htm"

dataset$los_angeles <- reactivePoll(
  intervalMillis = params$updateFreq, session=NULL, 
  checkFunc = function() get_url_date(url_la), 
  valueFunc = function() {
    out <- read_html(url_la) %>% 
      html_nodes("table") %>% 
      html_table() %>% 
      extract2(1) %>%
      select(X1, X2, X3) %>% 
      mutate(
        section = cumsum(as.numeric(str_detect(X1, "CITY/COMMUNITY"))),
        deaths = cumsum(as.numeric(str_detect(X1, "Deaths"))), 
        X2 = as.numeric(X2), 
        X3 = as.numeric(X3), 
        other_keep = str_detect(X1, "Long Beach") | str_detect(X1, "Pasadena")
      ) %>%
      filter(
        (section > 0 | (deaths == 0 & other_keep)), 
        ! str_detect(X1, "Under Investigation"), 
        ! str_detect(X1, "CITY/COMMUNITY")
      ) %>%
      select(-section, -other_keep, -deaths) %>% 
      set_colnames(c("city", "cases", "rate")) %>%
      mutate(
        pop = (cases / rate) * 100000, 
        CITY_TYPE = if_else(str_detect(city, "Unincorporated"), "Unincorporated", "City"),
        CITY_NAME = city %>% 
          map(~ str_replace_all(.x, "\\*", "")) %>%
          map(~ str_replace_all(.x, "Unincorporated - ", "")) %>%
          map(~ str_replace_all(.x, "Los Angeles - ", "")) %>%
          map(~ str_replace_all(.x, "City of ", "")) %>%
          map(~ str_replace_all(.x, "- ", "")) %>%
          unlist()
      ) %>%
      select(-city)
    
    update_dataset_dt_url("LA Local", url_la)
    
    out
  }
)
```

```{r visualization_options,context="server-start",cache=F,include=F}
palletes <- list(
  # Counts
  cases = "Reds", 
  active_cases = "Oranges",
  # Moving averages
  new_cases_ma = "YlOrRd", 
  cases_growth_rate_ma = "YlOrBr", 
  active_case_growth_rate_ma = "PiYG",
  # Demographics
  pop_density = "YlGn", 
  housing_density = "PuOr",
  occupancy_density = "BuPu",
  # Rates
  icu_rate = "magma", 
  vent_rate = "viridis",
  rate = "inferno", # infection_rate
  penetrance = "plasma",
  pos_rate = "RdYlGn", 
  tests_per_cap_ma = "RdPu"
)

get_ranges <- function(x, label) {
  minmax <- x %>%
    data.frame() %>% 
    select_if(is.numeric) %>% 
    ungroup() %>%
    gather(key="key", value="val") %>%
    filter(
      !is.na(val), !is.infinite(val), !is.nan(val)
    ) %>%
    group_by(key) %>% 
    summarize(
      min=min(val), 
      min_log = min(val[val > 0]),
      max=max(val)
    )
  
  ranges <- pmap(list(minmax$min, minmax$min_log, minmax$max), function(a, b, c) list(rng=c(a, c), log_rng=c(b, c)))
  names(ranges) <- minmax$key
  ranges
}

get_vis_elements <- function(x, label) reactive(label=label, {
  ranges <- get_ranges(x())
  
  list(
    "New Cases Moving Average" = list(
      field = "new_cases_ma",
      pal = quote(log10(new_cases_ma)), 
      legend_bins=5, 
      legend_vals=quote(log10(ranges[["new_cases_ma"]]$log_rng)), 
      legend_trans = labelFormat(transform=function(x) round(10^x), suffix = " new cases / day")
    ), 
    "Growth Rate Moving Average" = list(
      field = "cases_growth_rate_ma",
      pal = quote(log10(100 * cases_growth_rate_ma)), 
      legend_bins = 5, 
      legend_vals = quote(log10(100 * c(.01, 1.5))), 
      legend_trans = labelFormat(transform=function(x) round(10^x), suffix = " % / day")
    ),
    "Cases" = list(
      field = "cases",
      pal = quote(log10(cases)),
      legend_bins = 5,
      legend_vals = quote(log10(ranges[["cases"]]$log_rng)),
      legend_trans = labelFormat(transform=function(x) round(10^x))
    ),
    "Active Case Growth Rate Moving Average" = list(
      field = "active_case_growth_rate_ma",
      pal = quote(-active_case_growth_rate_ma), 
      legend_bins=5, 
      legend_vals=quote(-c(-.2, .3)), 
      legend_trans = labelFormat(transform=function(x) round(-x * 100), suffix = " % / day" )
    ),
    "Infection Rate" = list(
      field = "rate",
      pal = quote(log10(rate)),
      legend_bins = 5,
      legend_vals = quote(log10(ranges[["rate"]]$log_rng)),
      legend_trans = labelFormat(transform=function(x) round(10^x), suffix = " / 100,000 ppl")
    ),
    "Cases/Household" = list(
      field = "penetrance",
      pal = quote(penetrance),
      legend_bins = 4,
      legend_vals = quote(c(0, 1)),
      legend_trans = labelFormat(transform=identity, suffix = " cases / household")
    ),
    "Pop Density" = list(
      field = "pop_density",
      pal = quote(log10(pop_density)),
      legend_bins = 5,
      legend_vals = quote(log10(ranges[["pop_density"]]$log_rng)),
      legend_trans = labelFormat(transform=function(x) 10^x, suffix = " ppl / sqmi")
    ),
    "Active Cases" = list(
      field = "active_cases",
      pal = quote(log10(active_cases)),
      legend_bins=4,
      legend_vals=quote(log10(ranges[["active_cases"]]$log_rng)),
      legend_trans=labelFormat(transform=function(x) round(10^x))
    ),
    "ICU Rate" = list(
      field = "icu_rate",
      pal = quote(icu_rate), 
      legend_bins=4, 
      legend_vals=quote(c(0, 1)), 
      legend_trans=labelFormat(transform=identity, suffix=" ICU Admissions / Hospitalization")
    ), 
    "Vent Rate" = list(
      field = "vent_rate",
      pal = quote(vent_rate), 
      legend_bins=4, 
      legend_vals=quote(c(0, 1)), 
      legend_trans=labelFormat(transform=identity, suffix=" Ventilator / ICU Admission")
    ),
    "Daily Testing Moving Average" = list(
      field = "tests_per_cap_ma", 
      pal = quote(tests_per_cap_ma), 
      legend_bins = 3, 
      legend_vals = ranges[["tests_per_cap_ma"]]$rng, 
      legend_trans = labelFormat(transform=identity, suffix=" Tests / 100,000 ppl")
    ), 
    "Positive Test Rate" = list(
      field = "pos_rate", 
      pal = quote(-pos_rate), 
      legend_bins=4, 
      legend_vals = -c(0, 1), 
      legend_trans = labelFormat(transform=function(x) - x)
    )
  ) %>%
    keep(~ .$field %in% names(ranges)) %>%
    modify(function(x) {
      x$legend_vals <- eval(x$legend_vals)
      x$pallete <- palletes[[x$field]]
      x
    })
})

```

```{r map_functions,context="server-start",include=F}
update_map <- function(map, vis_options, map_name, input) {
  map %<>% clearShapes() %>% clearMarkers()
  
  for (selection in names(vis_options)) {
    vis_parts <- vis_options[[selection]]
    
    pallete <- colorNumeric(vis_parts$pallete, domain=vis_parts$legend_vals)
    
    map %<>% 
      addPolygons(
      opacity = 0.7,
      group = selection,
      weight = ~ if_else(hot_spot, 2, .1),
      color = ~ if_else(hot_spot, "red", "blue"),
      fillColor = ~ pallete(eval(vis_parts$pal)),
      fillOpacity = 0.7,
      label = ~popup,
      highlight = highlightOptions(
        weight=5, fillOpacity=1.0, bringToFront = TRUE
      )
   ) 
  }
  
  groups <- isolate(input[[paste0(map_name, "_groups")]]) 
  if (! is.null(groups)) {
    map %<>% adjust_legend(groups, vis_options)
  }
  
  map
}

adjust_legend <- function(map, groups, vis_options) {
  selection <- groups[1]
  
  if (! selection %in% names(vis_options)) {
    selection <- names(vis_options)[1]
    showGroup(map, selection)
  }

  vis_parts <- vis_options[[selection]]

  pallete <- colorNumeric(vis_parts$pallete, domain=vis_parts$legend_vals)
  
  map %>% 
     clearControls() %>%
     addLegend(title=selection, 
          pal=pallete, 
          group=selection,
          values=vis_parts$legend_vals,
          bins=vis_parts$legend_bins,
          labFormat=vis_parts$legend_trans, 
          position="bottomleft"
     )
}
```

```{r phony_inputs,include=F}
# This is used during testing so that reactive expressions that depend on input can function
if (! exists("input")) {
  input <- list(
    worlddate = Sys.Date() - 1, 
    worldscale = "linear", 
    worldmincases = 1,
    usdate = Sys.Date() - 1, 
    usscale = "State",
    usmincases = 1,
    cityselection = "New York",
    curve_flattening_min_cases = 1000
  )
  
  output <- list()
}

```

Introduction 
==================================

Row
----------------------------------

### Introduction 

```{r intro_text}
tagList(
  h2("Introduction"), 
  p("This app visualizes publicly available data regarding the progress of the COVID-19 pandemic. Its purpose is to consolidate varied data sources, and provide coherent and up-to-date visualizations of the data."),
  p("Click on the tabs to see different views."),
  h3("World Overview"),
  p("The world overview shows the progress of the pandemic by country, globally."),
  p("Regions where the rate of infection is accelerating (current exponential growth) are highlighted in red."),
  p("Click on a region to focus the charts below the map."), 
  h3("United States"),
  p("The US view shows detailed information about the pandemic by US State and County."),
  p("Use the icon in the upper right hand corner of the map to select data to view."),
  p("The 'Active Case Growth Rate Moving Average', for example, shows whether the burden on health care is increasing or decreasing in each region."), 
  p("The data formerly shown on the US Testing pane is now shown in a tab on this page."),
  h3("Cities"),
  p("The cities pane shows close-up views of New York City and the San Francisco Bay Area"), 
  h3("Curve Flattening"),
  p("This chart shows, for different regions, the number of new cases per day vs. the number of pre-existing cases, over time."),
  p("Its an indication of each region's effectiveness in stopping the spread.")
)

```

Row {data-height=20}
-----------------------------

The boxes below show the status of the data sources used to power this visualization:

Row {data-height=70}
-----------------------------

```{r show_data_status,context="server-start"}
data_status_box <- function(f, data_name, title) {
  renderValueBox({
    val <- tryCatch({
      rows <- nrow(f())
      if (rows > 0) {
        update_time <- datasetdt[[data_name]] 
        format(update_time, "OK %b %d, %Y %I:%M %p", tz="America/Los_Angeles")
      } else "Could not fetch data"
    }, 
    error = function(e) as.character(e)
    )
    
    valueBox(tags$p(val, style="font-size: 50%"), caption=title, color=if_else(str_starts(val, "OK"), "success", "warning"))
  })
}
```



### JH Data

```{r status_jh,context="server"}
output$status_jh <- data_status_box(world_cases_jh, "Confirmed Cases (JH)", "Johns Hopkins Global Data")
```

```{r status_jh_out}
valueBoxOutput("status_jh")
```

### US State & County Data

```{r status_us,context="server"}
output$status_us <- data_status_box(dataset$cases_state_nyt, "NYT States", "New York Times US State & County Tracker")
```

```{r status_us_out}
valueBoxOutput("status_us")
```

### Interventions

```{r status_interventions,context="server"}
output$status_interventions <- data_status_box(dataset$interventions, "Interventions", "Keystone Strategy Intervention Data")
```

```{r status_interventions_out}
valueBoxOutput("status_interventions")
```




### COVID Tracker

```{r status_covid_track,context="server"}
output$status_covid_track <- data_status_box(dataset$covid_track, "COVID Track", "COVID Tracker")
```

```{r status_covid_track_out}
valueBoxOutput("status_covid_track")
```


Row {data-height=70}
-----------------------------

### NY DOH

```{r status_ny,context="server"}
output$status_nydoh <- data_status_box(dataset$nyzipcode, "NYC Testing by Zipcode", "New York Dept. of H.")
```

```{r status_nyc_out}
valueBoxOutput("status_nydoh")
```

### SF

```{r status_sf,context="server"}
output$status_sf <- data_status_box(dataset$sfzipcode, "SF Testing by Zipcode", "San Francisco Dept. of Pub. H.")
```


```{r status_sf_out}
valueBoxOutput("status_sf")
```

### Alameda

```{r status_alameda,context="server"}
output$status_alameda <- data_status_box(dataset$alameda, "Alameda", "Alameda County")
```


```{r status_alameda_out}
valueBoxOutput("status_alameda")
```

### Los Angeles Local

```{r status_la_server,context="server"}
output$status_la <- data_status_box(dataset$los_angeles, "LA Local", "Los Angeles Open Data")
```

```{r status_la}
valueBoxOutput("status_la")
```

World Overview
=======================================================================


Inputs {.sidebar}
-----------------------------------------------------------------------

### Input

```{r world_input,context="server",include=F}
output$worldoverviewinputs <- renderUI({
  cases <- world_cases_jh()
  
  tagList(
    p("Use the icon in the upper right corner of the map to change viewed metric."), 
    p("Click on locations to zoom the charts."),
    p("Red outlines indicate regions where the rate of infection is accelerating (new cases have been greater than the trailing average for three consecutive days)."),
    sliderInput(
      "worlddate",
      "Date",
      min =  min(cases$date),
      max = max(cases$date),
      value = max(cases$date),
      timeFormat = "%Y-%m-%d",
      animate = T
    ),
    radioButtons(
      "worldscale",
      "Scale",
      choices = list(Linear = "linear",
                     Logarithmic = "logarithmic")
    ),
    sliderTextInput(
      "worldmincases", 
      "Minimum Number of Cases", 
      choices = 10^(0:4),
      selected = 1
    )
  )
})
```
```{r world_input_output}
#radioButtons("worlduslevel", "US Detail", choices=c("Country", "State", "County"), selected="State")
uiOutput("worldoverviewinputs")
```


Row
-----------------------------------------------------------------------
### World Map

```{r worldmap_data,context="server",include=F}
world_cases <- reactive({
  req(input$worlddate)
  
  todisplay <- world_cases_jh() %>% 
    dplyr::filter(date == input$worlddate)

  todisplay %>% 
    inner_join(locations) %>%
    ungroup() %>% 
    mutate(
      popup=paste0('<font color="blue">', 
                   case_when(
                     ! is.na(Subsublocation) ~ paste0(Subsublocation, ", ", Sublocation, ", ", Location), 
                     ! is.na(Sublocation) ~ paste0(Sublocation, ", ", Location), 
                     TRUE ~ Location
                   ),
                   "</font><br/>", 
                   text_case, 
                   "<hr/>", 
                   text_growth, 
                   "<hr/>",
                   text_medical
      ),
      popup=map(popup, HTML)
    ) 
})

world_polygons <- reactive({
  world_geoms %>% 
    select(-Location, -Sublocation) %>% 
    inner_join(world_cases())
})

world_circles <- reactive({
  locs_to_exclude <- world_polygons() %>% use_series(loc_id) 
  
  isolate(world_cases()) %>% 
    filter(! loc_id %in% locs_to_exclude)
})
```

```{r world_vis_elements,context="server",include=F}
world_vis_options <- get_vis_elements(world_cases_jh, "world_vis_options")
```

```{r worldmap,context="server",include=F}
output$worldview <- renderLeaflet({
  req(world_vis_options)
  leaflet(
    options=leafletOptions(
      minZoom=2,
      worldCopyJump=T
    )
  ) %>% 
    addProviderTiles(providers$CartoDB.Positron) %>%
    addLayersControl(baseGroups=names(isolate(world_vis_options())))
})

sizer <- 2000

observe(label="update_world_map", {
  polys <- world_polygons() 
  circles <- world_circles() 
  vis_options <- world_vis_options()
  
  map <- leafletProxy(data=polys, "worldview", deferUntilFlush=T) %>%
    update_map(vis_options, "worldview", input)
  
  map %>%
    addCircles(group="Confirmed", 
               data=circles, 
               weight=0, opacity=0, fillOpacity = 0.3, 
               color="Blue", 
               radius = ~(sqrt(cases) * sizer),
               label=~popup)
})

observeEvent(input$worldview_groups, 
             label="handle_worldmap_legend", {
  
  req(world_vis_options)
  map <- leafletProxy('worldview') %>% 
    clearControls() 
  
  selection <- isolate(input$worldview_groups)
  
  adjust_legend(map, selection, world_vis_options())
})
```
```{r worldmap_output}
leafletOutput("worldview")
```

```{r worldview_handle_clicks,context="server",include=F}
click_d_threshold <- 20 

world_click_state <- reactive(label="worldmapclick", {
  if (is.null(input$worldview_click)) {NA}
  else {
    lat <- input$worldview_click$lat
    lng <- input$worldview_click$lng
    
    target <- st_point(x=c(lng, lat), dim=c("XY"))
    
    poly_match <- world_geoms %>%
      filter(map_lgl(bbox, ~ between(target[1], .x$xmin, .x$xmax) & between(target[2], .x$ymin, .x$ymax))) %>% 
      filter(st_within(target, geometry, sparse=F, prepared=F)) 
    
    if (nrow(poly_match) > 0) return(poly_match$loc_id[1])

    out <- locations %>% filter(
      is.na(Subsublocation), 
      ! loc_id %in% world_geoms$loc_id, 
      Location != "US" | is.na(Sublocation)
    ) %>%
      mutate(
        pt = map2(lng, lat, ~st_point(c(.x, .y), dim="XY")), 
        d = unlist(map(pt, ~ st_distance(target, .x)))
      ) %>%
      top_n(n=1, wt=-d)
    
    if (out$d[1] < click_d_threshold) {out$loc_id[1]}
    else {NA}
  }
})
```

```{r world_case_summary,context="server",include=F}
world_case_summary <- reactive(label="world_case_summary", {
  cases_input <- world_cases_jh()
  click_state <- world_click_state()
  
  (if (is.na(click_state)) {
    cases_input %>% 
     ungroup() %>%
     group_by(date) %>%
     #select(-loc_id) %>%
     summarize_if(is.numeric, ~sum(., na.rm=T)) %>% 
      arrange(date) %>% 
      supplement_data_base() %>%
      supplement_data_for_medical() %>% 
      supplement_data_for_growth()
  } else {
    cases_input %>% 
      filter(loc_id == click_state) %>% 
      ungroup()
  }) %>% 
    filter(cases >= input$worldmincases)
})


world_click_name <- reactive({
  click_state = world_click_state()
  if (is.na(click_state)) {"Global"}
  else {
    locations %>%
      filter(loc_id == click_state) %>%
      mutate(
        name = case_when(
          is.na(Sublocation) ~ Location,
          TRUE ~ paste0(Sublocation, " ", Location)
        )
      ) %>%
      use_series(name)
  }
})
```

Row {data-height=300}
----------------------------------------------------

### Cases

```{r worldcases,context="server",include=F}
output$worldcases <- renderHighchart({
  req(input$worldscale)
  highchart()  %>%
    hc_title(text = paste0("Cases (", isolate(world_click_name()), ")")) %>%
    hc_yAxis(title = "", 
             type = input$worldscale,
             min = if_else(input$worldscale == "linear", 0, 1)) %>%
    hc_xAxis(type = "datetime") %>%
    hc_add_series(
      type = "line",
      mapping = hcaes(x = date, y = val, group = Series),
      data = world_case_summary() %>%
        select(
          date,
          Cases = cases,
          Deaths = deaths,
          Recovered = recovered
        ) %>%
        mutate(Active = Cases - Deaths - Recovered) %>%
        gather(key = "Series", value = "val",-date),
        marker=list(enabled=F)
    ) %>%
    hc_tooltip(shared=TRUE)
})
```

```{r worldcasesoutput}
highchartOutput("worldcases")
```

### New Cases Per Day

```{r worldnewcases,context="server"}
output$dailynewcases <- renderHighchart({
  req(input$worldscale)
  highchart()  %>%
    hc_title(text = paste0("New Cases Per Day (", isolate(world_click_name()), ")")) %>%
    hc_yAxis(title = "") %>%
    hc_xAxis(type = "datetime") %>%
    hc_add_series(
      type = "column",
      mapping = hcaes(x = date, y = New),
      data = world_case_summary() %>%
        select(date, New = cases_new),
      name = "New Cases"
    ) %>%
    hc_add_series(
      type="line", 
      color="red", 
      marker=list(enabled=F), 
      mapping = hcaes(x = date, y = new_cases_ma), 
      name=paste0(params$k, "-day moving average"), 
      data = isolate(world_case_summary())
    )
})
```

```{r worldnewcasesoutput}
highchartOutput("dailynewcases")
```

### Growth Rate (new cases / prior cases)

```{r world_growth,context="server"}
output$world_growth <- renderHighchart({
  req(input$worldscale)
  highchart()  %>%
    hc_title(text = paste0("Growth Rate (", isolate(world_click_name()), ")")) %>%
    hc_yAxis(title = "", 
             type="logarithmic",
             labels=list(
               format="{value} %"
             )) %>%
    hc_xAxis(type = "datetime") %>%
    hc_add_series(
      type="line", 
      marker=list(enabled=F), 
      data = world_case_summary() %>% 
        select(date, `Growth Rate` = cases_growth_rate, cases_growth_rate_ma) %>%
        gather(key="key", value="value", -date) %>%
        mutate(
          value = round(value * 100, 2),
          key = if_else(key == "cases_growth_rate_ma", paste0(params$k, "-day Rolling Average"), key)
        ), 
      mapping = hcaes(x = date, y = value, group=key),
      tooltip=list(
        shared=T, 
        pointFormat='<span style="color:{point.color}">●</span> {series.name}: <b>{point.y}</b> %<br/>.'
        )
    ) %>%
    hc_tooltip(shared=T)
})
```

```{r world_growth_output}
highchartOutput("world_growth")
```

United States
================================================

Inputs {.sidebar}
-----------------------------------------------------------------------

### Input

```{r usinput,context="server",include=F}
output$usinputs <- renderUI({
  cases <- dataset$cases_county_nyt()
  
  tagList(
    p("Use the icon in the upper right corner of the map to change viewed metric."), 
    p("Click on locations to zoom the charts."),
    p("Red outlines indicate regions where the rate of infection is accelerating (new cases have been greater than the trailing average for three consecutive days)"),
    sliderInput("usdate", "Date:",
                min=min(cases$date), 
                max=max(cases$date), 
                value=max(cases$date), 
                timeFormat="%Y-%m-%d", 
                animate=T),
    
    radioButtons("usscale", "Data Resolution", 
                 choices=c("State", "County"), 
                 selected="State"),
    
    radioButtons("uslog", "Scale", 
                 choices=list(
                   Linear="linear", 
                   Logarithmic="logarithmic"
                 ), 
                 selected="linear"),
    sliderTextInput(
      "usmincases", 
      "Minimum Number of Cases", 
      choices = 10^(0:3),
      selected = 100
    )
  )
})
```

```{r usinput_output}
uiOutput("usinputs")
```

Row
-----------------------------------------------

### US Map

```{r make_us_cases,context="server-start",include=F}
us_geography_data <- geometries %>% data.frame() %>%
  select(aland, housing_units, pop, loc_id)

process_us_cases <- function(x) us_geography_data %>%
  inner_join(x %>% 
        filter(cases > 0) %>%
        inner_join(locations) %>%
        rename(state = Sublocation, county = Subsublocation), 
      by="loc_id"
  ) %>%
  mutate(
    landsqmi = aland / 2591646,
    pop_density = pop / landsqmi,
    housing_density = housing_units / landsqmi,
    occupancy_density = pop / housing_units
  ) %>%
  group_by(loc_id) %>%
  arrange(date) %>%
  supplement_data_base() %>% 
  supplement_data_for_demographics() %>%
  supplement_data_for_growth() %>%
  mutate(
    popup = paste0(
      "<font color='blue'>", if_else(is.na(county), state, paste0(county, ", ", state)), "     ", format(date, "%B %d, %Y"), "</font><br/>",
      "<hr>",
      text_case, 
      "<hr/>", 
      text_growth,
      "<hr/>", 
      text_demographics
    )
  )

us_cases_state <- reactive(
  dataset$cases_state_nyt() %>% 
    left_join(dataset$covid_track() %>% 
                  select(date, loc_id, 
                         negativeIncrease, pending, positiveIncrease,
                         hospitalized = hospitalizedCurrently, 
                         icu = inIcuCurrently, 
                         vent = onVentilatorCurrently, 
                         recovered)
    ) %>% 
    process_us_cases() %>%
    mutate_at(vars(negativeIncrease, pending, positiveIncrease), ~ case_when(
      is.na(.) ~ 0L, 
      TRUE ~ .
    )) %>%
    mutate_at(vars(hospitalized, icu, vent, recovered), ~ na.locf(., na.rm=F)) %>%     
    supplement_data_for_medical() %>%
    supplement_data_for_testing() %>%
    mutate(
      popup = paste0(popup, 
                     "<hr/>",
                     text_testing, "<hr/>",
                     text_medical)
    )
)

us_cases_county <- reactive(
  dataset$cases_county_nyt() %>% 
    process_us_cases() %>%
    mutate(
      negativeIncrease = NA, 
      pending = NA, 
      positiveIncrease = NA, 
      hospitalized = NA, 
      icu = NA, 
      vent = NA, 
      recovered = NA
    ) %>% 
    supplement_data_for_medical() %>%
    supplement_data_for_testing() %>%
    mutate(popup = paste0(popup, "<hr/>", text_demographics))
)
```

```{r usmap_data_filtration,context="server",include=F}
us_cases_state_county <- reactive({
  req(input$usscale)
  scale <- input$usscale
  
  (
    if (scale == "County") us_cases_county()
    else us_cases_state()
  ) %>% 
    filter(
      cases >= input$usmincases
    ) %>%
    mutate(
      popup = map(popup, HTML)
    )
})

us_cases_date_filtered <- reactive({
  req(input$usdate)

  us_cases_state_county() %>% 
    filter(
      date == input$usdate
    ) 
})

us_cases_with_geo <- reactive(
  geometries %>% 
    inner_join(us_cases_date_filtered())
)
```

```{r usmap_vis_elements,context="server",include=F}
us_vis_options <- get_vis_elements(us_cases_state_county, "us_vis_options")
```

```{r usmap,context="server",include=F}
output$usview <- renderLeaflet({
  usbox <- st_bbox(continental_us$us)
  uscenter <- st_centroid(continental_us$us)
  
  leaflet(
    options=leafletOptions(
      minZoom=3
    )
  ) %>% 
    addProviderTiles(providers$CartoDB.Positron) %>%
    setMaxBounds(usbox[1], usbox[2], usbox[3], usbox[4]) %>%
    setView(lat=uscenter[[1]][2], lng=uscenter[[1]][1], zoom=3) 
})

observe(label="update_usmap", {
  vis_options <- us_vis_options()
  
  map <- us_cases_with_geo() %>% 
    leafletProxy(data=., "usview", deferUntilFlush=T) %>%
    update_map(vis_options, "usview", input)

  map %<>%
      addLayersControl(baseGroups = names(vis_options))
})

observeEvent(input$usview_groups, 
             label="handle_usmap_legend", {
  
  map <- leafletProxy('usview') %>% 
    clearControls() 
  
  selection <- isolate(input$usview_groups)
  
  adjust_legend(map, selection, req(us_vis_options()))
})
```

```{r usmap_output}
leafletOutput("usview")
```


Row
------------------------------------------------------------------

###

```{r us_detect_click,context="server",include=F}
click_state_name <- reactiveVal("U.S.", label="us_click_name") 

region_click_state <- reactive(label="usmapclick", {
  
  if (is.null(input$usview_click)) {
    click_state_name("U.S.")
    NA
  } else {
    lat <- input$usview_click$lat
    lng <- input$usview_click$lng
    
    target <- st_point(x=c(lng, lat), dim=c("XY"))
    
    out <- req(us_cases_with_geo()) %>% 
        filter(map_lgl(bbox, ~ between(target[1], .x$xmin, .x$xmax) & between(target[2], .x$ymin, .x$ymax))) %>% 
        filter(st_within(target, geometry, sparse=F, prepared=F)) %>% 
        select(state, county, loc_id)
    if (nrow(out) == 0) {
      click_state_name("U.S.")
      NA
    } else {
      name <- if_else(is.na(out$county[1]), out$state[1],
            paste0(out$county[1], ", ", out$state[1]))
      click_state_name(name)
      out
    }
  }
})
```

```{r data_us_case_sumary,context="server",include=F}
us_case_summary <- reactive(label="us_case_summary", {
  click_state <- region_click_state()

  (if (is.na(click_state)) {
    us_cases_state() %>% 
      ungroup() %>% 
      group_by(date) %>% 
      summarize_if(is.numeric, ~sum(., na.rm=T)) %>%
      supplement_data_base() %>%
      supplement_data_for_growth() %>%
      supplement_data_for_testing() %>%
      filter(cases >= req(input$usmincases))
  } else {
    us_cases_state_county() %>% ungroup() %>% 
      filter(loc_id == click_state$loc_id[1])
  }) %>%
    select(date, Cases=cases, Deaths=deaths, 
           Hospitalized=hospitalized, ICU=icu, 
           Ventilator=vent, Recovered = recovered, 
           cum_negative, pending, negativeIncrease, cum_pos_rate, pos_rate_ma, 
           `New Cases` = cases_new, new_cases_ma, cases_growth_rate, cases_growth_rate_ma) 
  
})
```

```{r us_cumulative,context="server"}
output$uscaseslinear <- renderHighchart(
  highchart() %>% 
    hc_title(text=paste0("Cases, Hosp. and Deaths (", isolate(click_state_name()), ")")) %>%
    hc_yAxis(title="", type=req(input$uslog), 
             min = if_else(isolate(input$uslog) == "linear", 0, 1)
             ) %>%
    hc_xAxis(type="datetime") %>% 
    hc_add_series(
      type="line",
      marker=list(enabled=F), 
      data=req(us_case_summary()) %>% 
        select(date, Cases, Deaths, Hospitalized, ICU, Ventilator, Recovered) %>% 
        gather(key="Series", value="val", -date) %>%
        filter(val > 0), 
      mapping=hcaes(x=date, y=val, group=Series)
    ) %>%
    hc_tooltip(shared=T)
)
```


```{r us_daily_new_cases,context="server",include=F}
output$usdailynewcases <- renderHighchart({
  highchart() %>% 
    hc_title(text=paste0("Daily New Cases (", isolate(click_state_name()), ")")) %>%
    hc_xAxis(type="datetime") %>%
    hc_yAxis(title="", type=req(input$uslog), min=1) %>% 
    hc_add_series(type="column", 
                  data=req(us_case_summary()), 
                  mapping=hcaes(x=date, y=`New Cases`),
                  name="New Cases") %>%
    hc_add_series(
      type="line", 
      color="red", 
      marker=list(enabled=F), 
      data=isolate(isolate(us_case_summary()) %>% select(date, new_cases_ma)),
      mapping=hcaes(x=date, y=new_cases_ma), 
      name=paste0(params$k, "-day moving average")
    )
})
```


```{r us_growth,context="server",include=F}
output$us_growth_rate <- renderHighchart(
  highchart() %>% 
    hc_title(text=paste0("Growth Rate (", req(isolate(click_state_name())), ")")) %>%
    hc_xAxis(type="datetime") %>%
    hc_yAxis(title="", type="logarithmic", 
             labels=list(
               format="{value} %"
             )) %>% 
    hc_add_series(
      type="line", 
      marker=list(enabled=F), 
      data=req(us_case_summary()) %>% 
        select(
          date, `Growth Rate` = cases_growth_rate, cases_growth_rate_ma
        ) %>% 
        gather(key="key", value="value", -date) %>%
        mutate(
          value = round(value * 100, 2),
          key = if_else(key == "cases_growth_rate_ma", paste0(params$k, "-day Moving Average"), key)
        ),
      mapping=hcaes(x=date, y=value, group=key),
      tooltip=list(
        shared=T, 
        pointFormat='<span style="color:{point.color}">●</span> {series.name}: <b>{point.y}</b> %<br/>.'
        )
    ) %>%
    hc_tooltip(shared=T)
)
```

```{r us_testing_cumulative,context="server",include=F}
output$ustesting <- renderHighchart(
  highchart()  %>%
    hc_plotOptions(column=list(stacking="normal")) %>%
    hc_title(text=paste0("Cumulative Testing (", isolate(click_state_name()), ")")) %>%
    hc_yAxis(title="", min=0) %>%
    hc_xAxis(type="datetime") %>% 
    hc_add_series(data = req(us_case_summary()) %>% 
                    select(date, Positive=Cases, Negative=cum_negative, Pending=pending) %>% 
                    gather(key="Series", val="val", -date), 
                  type="column", 
                  mapping=hcaes(x=date, y=val, group=Series, fill=Series)) %>%
    hc_tooltip(shared=T)
)
```


```{r us_testing_daily,context="server",include=F}
output$ustestinginc <- renderHighchart(
  highchart()  %>%
    hc_plotOptions(column=list(stacking="normal")) %>%
    hc_title(text=paste0("Daily Testing (", isolate(click_state_name()), ")")) %>%
    hc_yAxis(title="", min=0) %>%
    hc_xAxis(type="datetime") %>% 
    hc_add_series(data = req(us_case_summary()) %>% 
                    select(date, Positive=`New Cases`, Negative=negativeIncrease) %>% 
                    gather(key="Series", val="val", -date), 
                  type="column", 
                  mapping=hcaes(x=date, y=val, group=Series, fill=Series)) %>%
    hc_tooltip(shared=T)
)
```

```{r us_testing_pos_rate,context="server",include=F}
output$ustestingrate <- renderHighchart(
  highchart()  %>%
    hc_plotOptions(column=list(stacking="normal")) %>%
    hc_title(text=paste0("Positive Rate (", isolate(click_state_name()), ")")) %>%
    hc_yAxis(title="", min=0) %>%
    hc_xAxis(type="datetime") %>% 
    hc_add_series(data = req(us_case_summary()) %>% 
                    filter(date >= dmy("1/3/2020")) %>% 
                    select(date, `Cumulative`= cum_pos_rate, `Trailing Days`=pos_rate_ma) %>% 
                    gather(key="Series", value="value", -date), 
                  type="line", 
                  mapping=hcaes(x=date, y=value, group=Series)) %>%
    hc_tooltip(shared=T)
)
```


```{r curve_flattening_data_work,context="server-start",include=F}
grouped_interventions <- reactive(
  dataset$interventions() %>% 
    group_by(loc_id, date) %>% 
    summarize(intervention = paste(intervention, collapse=", "))
)

interventions_to_list <- function(x) x %>% 
  mutate(
      data = pmap(list(cases, new_cases_ma, intervention, date), function(cases, new_cases_ma, intervention, date, ...) {
        list(
          x = cases, 
          y = round(new_cases_ma), 
          marker = list(
            enabled = ! is.na(intervention),
            symbol = case_when(
              str_detect(intervention, "lockdown") ~ "triangle", 
              str_detect(intervention, "shelter_in_place") ~ "triangle-down", 
              str_detect(intervention, "non-essential_services_closure") ~ "square", 
              str_detect(intervention, "social_distancing") ~ "diamond", 
              TRUE ~ "circle"
            )
          ), 
          date = date, 
          intv = intervention 
        )
      })
    ) %>% 
    select(-intervention, -new_cases_ma, -date) %>%
    group_by(name) %>% 
    arrange(cases) %>% 
    summarize(
      dt = list(data)
    ) %>% 
    mutate(
      series = map2(dt, name, ~ list(
          type = "line", 
          data = .x, 
          name = .y, 
          id = .y
        )
      )
    ) %>%
    use_series(series)
```

```{r us_curve_flattening,context="server",include=F}
curve_flattening_for_us <- reactive({
  click_state <- region_click_state()
  state_cases <- us_cases_state()
  cases_with_interventions <- NA
  
  if (is.na(click_state)) {
    cases_with_interventions <- state_cases
  } else {
    chosen_state <- click_state$state
    
    cases_with_interventions <- state_cases %>%
      filter(state == chosen_state) %>%
      bind_rows(
        us_cases_county() %>%
          filter(state == chosen_state)
      )
  }
  
  cases_with_interventions %>% 
    left_join(grouped_interventions()) %>%
    mutate(
      name = case_when(
        is.na(county) ~ state, 
        TRUE ~ county
      )
    ) %>%
    group_by(loc_id) %>%
    filter(max(cases) >= input$usmincases) %>%
    interventions_to_list()
})

output$us_curve_flattening <- renderHighchart({
  click_state <- isolate(region_click_state())
  name <- "Curve Flattening (By State)"
  if (! is.na(click_state)) name <- paste0("Curve Flattening (", click_state$state[1], ")")
  
  highchart()  %>%
    hc_title(text=name) %>%
    hc_yAxis(title="New Cases Per Day (MA)", min=1, type="logarithmic") %>%
    hc_xAxis(title="Cases", type="logarithmic") %>% 
    hc_add_series_list(curve_flattening_for_us()) %>%
    hc_tooltip(
      shared=F, 
      headerFormat='<span style="font-size: 10px">{series.name}</span><br/>',
      pointFormat="{point.date}<br/>{point.intv}<br/>Cases: {point.x}  New Cases MA: {point.y}"
    )
})
```

```{r us_charts}
tabsetPanel(type="tabs", 
            tabPanel("Growth", 
                     fluidRow(
                       column(4, highchartOutput("uscaseslinear")),
                       column(4, highchartOutput("usdailynewcases")),
                       column(4, highchartOutput("us_growth_rate"))
                     )
            ), 
            tabPanel("Testing", 
                     fluidRow(
                       column(4, highchartOutput("ustesting")),
                       column(4, highchartOutput("ustestinginc")), 
                       column(4, highchartOutput("ustestingrate"))
                       
                     )
            ),
            tabPanel("Curve Flattening", 
                     highchartOutput("us_curve_flattening")
            )
)
```


Cities 
===================================================

Inputs {.sidebar}
-----------------------------------------------------------------------

### Input

```{r city_datasets,context="server-start",include=F}
zips_with_pop <- zip_geoms %>% data.frame() %>% 
  select(zipcode, pop) %>%
  left_join(zips %>% data.frame() %>% select(zipcode, aland10))

process_city <- function(x) x %>%
  mutate(
    pop = round(pop),
    pop_density = round(pop / landsqmi)
  ) %>%
  supplement_data_base() %>% 
  supplement_data_for_demographics() %>%
  filter(cases > 0) %>% 
  mutate(
    rate = round((cases / pop) * 100000),
    hot_spot = F,
    popup = paste0(
      name,
      "<hr/>",
      text_demographics, 
      "<hr/>", 
      text_case
    ),
    popup = map(popup, HTML)
  ) %>% 
  ungroup() 

city_sfbay <- reactive(
  bind_rows(
    dataset$sfzipcode(),
    dataset$alameda()
  ) %>% 
    mutate(
      zipcode = as.character(zipcode)
    ) %>% 
    bind_rows(san_mateo %>% rename(cases=count)) %>%
    mutate(
      negative = NA_real_, 
      housing_units = NA_real_
    ) %>% 
    left_join(zips_with_pop) %>%
    mutate(
      landsqmi = aland10 / 2591646,
      name = paste0("<font color='blue'>Zipcode: ", zipcode, "</font><br/>"),
    ) %>%
    process_city()
)

city_nyc <- reactive(
  dataset$nyzipcode() %>%
    mutate(
      zipcode = as.character(zipcode)
    ) %>%
    left_join(zips_with_pop) %>%
    mutate(
      landsqmi = aland10 / 2591646,
      negative = NA_real_, 
      housing_units = NA_real_,
      name = paste0("<font color='blue'>Zipcode: ", zipcode, "</font><br/>"),
    ) %>%
    process_city()
)

city_losangeles <- reactive(
  dataset$los_angeles() %>%
    left_join(
      la_polys %>% data.frame() %>% select(CITY_NAME, CITY_TYPE, landsqmi = area_sm)
    ) %>%
    mutate(
      negative = NA_real_, 
      housing_units = NA_real_,
      hospitalized = NA_real_,
      deaths = NA_real_,
      name = paste0("<font color='blue'>", CITY_NAME, "</font><br/>"),
    ) %>%
    process_city()
)
```

```{r city_input,context="server",include=F}
output$cityinputs <- renderUI({
  tagList(
    shinyWidgets::radioGroupButtons(
      "cityselection", 
      label="Choose City", 
      choices=c("New York", "San Francisco", "Los Angeles"),
      selected = "New York",
      direction="vertical",
      individual = TRUE, 
      #status = "info", 
      # checkIcon = list(
      #yes = tags$i(class = "fa fa-check-square", 
      #             style = "color: steelblue"),
      #no = tags$i(class = "fa fa-square-o", 
      #            style = "color: steelblue")
    )
  )
})
```
```{r city_input_output}
#radioButtons("worlduslevel", "US Detail", choices=c("Country", "State", "County"), selected="State")
uiOutput("cityinputs")
```

Row 
-----------------------------------------

```{r city_data,context="server",include=F}
city_data <- reactive({
  city <- req(input$cityselection)
  
  if (city == "Los Angeles") la_polys %>% inner_join(city_losangeles())
  else {
    x <- (
      if (city == "New York") city_nyc()
      else city_sfbay()
    )
    zip_geoms %>% inner_join(x, by="zipcode")
  }
})

city_vis_options <- get_vis_elements(city_data,
                                     "city_vis_options")

```

### City View

```{r city_map,context="server",include=F}
output$cityview <- renderLeaflet({
  #vis_options <- req(isolate(city_vis_options()))
  
  leaflet() %>% 
    addProviderTiles(providers$CartoDB.Positron) #%>%
    #addLayersControl(baseGroups = names(vis_options))
})

observe(label="update_citymap", {
  vis_options <- req(city_vis_options())
  
  geoms <- req(city_data())
  
  box <- st_bbox(geoms$geometry)
  center <- st_centroid(geoms$geometry)
  
  geoms %>% 
    leafletProxy(data=., mapId = "cityview", deferUntilFlush=T) %>% 
    setMaxBounds(box[[1]], box[[2]], box[[3]], box[[4]]) %>%
    setView(lat=center[[1]][2], lng=center[[1]][1], zoom=10) %>%
    clearControls() %>% 
    update_map(vis_options, "cityview", input) %>%
    addLayersControl(baseGroups = names(vis_options))
})

observeEvent(input$cityview_groups, 
             label="handle_citymap_legend", {
  
  map <- leafletProxy('cityview') %>% 
    clearControls() 
  
  selection <- isolate(input$cityview_groups)
  
  adjust_legend(map, selection, req(city_vis_options()))
})
```

```{r citymap_output}
leafletOutput("cityview")
```

Curve Flattening
=========================================

Inputs {.sidebar}
-----------------------------------------------------------------------

```{r curve_flattening_inputs_server,context="server"}
output$curve_flattening_inputs <- renderUI({
  tagList(
    p("These charts show regions' progress in 'flattening the curve' by reducing the number of new cases per day as the number of cases increases."), 
    p("A flat horizontal line implies linear growth"), 
    p("A line moving down implies that the growth rate is dropping"), 
    p("Points on the State and County chart correspond to imposed interventions."),
    radioButtons("curve_flattening_resolution", label="Resolution", choices=c("Countries", "State", "County"), selected="Countries"),
    sliderTextInput(
      "curve_flattening_min_cases", 
      "Minimum Number of Cases", 
      choices = 10^(0:5),
      selected = 10000
    )
  )
})
```

```{r curve_flattening_inputs_output}
uiOutput("curve_flattening_inputs")
```

Row
--------------------------------------

```{r curve_flattening_data,context="server"}
curve_flattening_data <- reactive({
  resolution <- req(input$curve_flattening_resolution)
  
  x <- if (resolution == "Countries") {
    world_cases_jh() %>% 
      select(loc_id, cases, date, new_cases_ma) %>% 
      filter(
        cases > input$curve_flattening_min_cases, 
        ! is.na(new_cases_ma)
      ) %>% 
      left_join(locations %>% select(Location, Sublocation, loc_id)) %>% 
      mutate(
        name = if_else(is.na(Sublocation), Location, paste0(Sublocation, ", ", Location)),
        intervention = NA,
        new_cases_ma = round(new_cases_ma)
      ) %>%
      ungroup() %>% 
      select(name, cases, new_cases_ma, date, intervention) 
  } else {
    (
      if (resolution == "State") us_cases_state()
      else us_cases_county()
    ) %>% 
      filter(
        cases > input$curve_flattening_min_cases, 
        ! is.na(new_cases_ma)
      ) %>% 
      mutate(
        new_cases_ma = round(new_cases_ma),
        name = case_when(
          resolution == "State" ~ state, 
          TRUE ~ paste0(county, ", ", state)
      )) %>% 
      select(name, cases, new_cases_ma, date) %>%
      left_join(grouped_interventions()) 
  }

  x %>% interventions_to_list()
})
```

### Curve Flattening (# of cases vs. `r params$k`-day moving average new cases/day)

```{r curve_flattening,context="server"}
output$curve_flattening <- renderHighchart(
  highchart() %>%
    hc_xAxis(title=list(text="Cases"), type="logarithmic") %>%
    hc_yAxis(title=list(text="New Cases"), type="logarithmic", min=100) %>% 
    hc_add_series_list(
      curve_flattening_data()
    ) %>%
    hc_tooltip(
      shared=F, 
      headerFormat='<span style="font-size: 10px">{series.name}</span><br/>',
      pointFormat="{point.date}<br/>{point.intv}<br/>Cases: {point.x}  New Cases MA: {point.y}"
    )
)
```

```{r curve_flattening_output}
highchartOutput("curve_flattening")
```